"""Backward-compatible constants exported from the canonical specs module."""

from circuit_specs import (
    ADDER_LAYOUT,
    BCD_CODE_SPACE,
    COUNTER_LAYOUT,
    COUNTER_STATE_COUNT,
    DECODER_LAYOUT,
    DEFAULT_ENCODER_OFFSET,
    ENCODER_LAYOUT,
    ENCODER_TENS_OUTPUTS,
    ENCODER_UNITS_OUTPUTS,
    MAX_ENCODER_SOURCE_VALUE,
    SUBTRACTOR_LAYOUT,
)

SUBTRACTOR_INPUTS = SUBTRACTOR_LAYOUT.input_width
DECODER_INPUTS = DECODER_LAYOUT.input_width
ENCODER_INPUTS = ENCODER_LAYOUT.input_width
ADDER_INPUTS = ADDER_LAYOUT.input_width
COUNTER_INPUTS = COUNTER_LAYOUT.input_width

BCD_BASE = 10
BCD_DIGIT_MAX = 9
BCD_STATE_COUNT = BCD_CODE_SPACE

COUNTER_MAX_STATE = COUNTER_STATE_COUNT
ENCODER_MAX_INPUT_VALUE = MAX_ENCODER_SOURCE_VALUE

OFFSET_N = DEFAULT_ENCODER_OFFSET

SUBTRACTOR_VARIABLES = SUBTRACTOR_LAYOUT.input_names
DECODER_INPUT_VARIABLES = DECODER_LAYOUT.input_names
DECODER_OUTPUT_VARIABLES = DECODER_LAYOUT.output_names
ADDER_INPUT_VARIABLES = ADDER_LAYOUT.input_names
ADDER_OUTPUT_VARIABLES = ADDER_LAYOUT.output_names
ENCODER_INPUT_VARIABLES = ENCODER_LAYOUT.input_names
ENCODER_TENS_OUTPUTS = ENCODER_TENS_OUTPUTS
ENCODER_UNITS_OUTPUTS = ENCODER_UNITS_OUTPUTS
COUNTER_STATE_VARIABLES = COUNTER_LAYOUT.input_names
COUNTER_OUTPUT_VARIABLES = COUNTER_LAYOUT.output_names
